In [12]:
'''
    --- IMPORT DATA ---
'''

import pandas as pd


df = pd.read_csv("output.csv")

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4093 entries, 0 to 4092
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   _id                    4093 non-null   object
 1   id                     4093 non-null   object
 2   trip_id                4093 non-null   object
 3   schedule_relationship  4093 non-null   object
 4   route_id               4093 non-null   object
 5   direction_id           539 non-null    float64
 6   latitude               4093 non-null   float64
 7   longitude              4093 non-null   float64
 8   odometer               4093 non-null   float64
 9   speed                  3801 non-null   float64
 10  current_stop_sequence  4093 non-null   object
 11  current_status         4093 non-null   int64
 12  timestamp              4093 non-null   object
 13  stop_id                4093 non-null   int64
dtypes: float64(5), int64(2), object(7)
memory usage: 447.8+ KB

In [13]:
df.columns

Index(['_id', 'id', 'trip_id', 'schedule_relationship', 'route_id',
       'direction_id', 'latitude', 'longitude', 'odometer', 'speed',
       'current_stop_sequence', 'current_status', 'timestamp', 'stop_id'],
      dtype='object')

In [14]:
import numpy as np

conditions = [
    df['speed'].between(41, np.inf),
    df['speed'].between(31, 40),
    df['speed'].between(21, 30),
    df['speed'].between(16, 20),
    df['speed'].between(1, 15)
]
congestion_levels = [0, 1, 2, 3, 4]
df['congestion_level'] = np.select(conditions, congestion_levels, default=2)

In [15]:
list(df.columns)

['_id',
 'id',
 'trip_id',
 'schedule_relationship',
 'route_id',
 'direction_id',
 'latitude',
 'longitude',
 'odometer',
 'speed',
 'current_stop_sequence',
 'current_status',
 'timestamp',
 'stop_id',
 'congestion_level']

In [16]:
df = df.dropna()
df

,_id,id,trip_id,schedule_relationship,route_id,direction_id,latitude,longitude,odometer,speed,current_stop_sequence,current_status,timestamp,stop_id,congestion_level
1,656c8b23cf3742cf5526e478,3f6631d0-bf40-448f-ab56-0b968ddaad17,aecd6920-d909-4f9b-9abd-975082fda027,SCHEDULED,1615e5c0-3157-4f13-9e78-011638725e02,1.0,44.366657,-79.663040,164691300.0,11.828447,IN_TRANSIT_TO,1701612287,6acc2847-34d9-4071-97a9-bde024231b42,2202,4
7,656c8b43cf3742cf5526e47e,3f6631d0-bf40-448f-ab56-0b968ddaad17,aecd6920-d909-4f9b-9abd-975082fda027,SCHEDULED,1615e5c0-3157-4f13-9e78-011638725e02,1.0,44.366300,-79.662544,164691400.0,70.000000,IN_TRANSIT_TO,1701612317,6acc2847-34d9-4071-97a9-bde024231b42,2202,0
13,656c8b63cf3742cf5526e484,3f6631d0-bf40-448f-ab56-0b968ddaad17,aecd6920-d909-4f9b-9abd-975082fda027,SCHEDULED,1615e5c0-3157-4f13-9e78-011638725e02,1.0,44.364796,-79.660645,164691600.0,15.807654,IN_TRANSIT_TO,1701612347,1ac5ab52-85b6-4f0e-a801-72eea8e02d0d,2202,2
19,656c8b83cf3742cf5526e48a,3f6631d0-bf40-448f-ab56-0b968ddaad17,aecd6920-d909-4f9b-9abd-975082fda027,SCHEDULED,1615e5c0-3157-4f13-9e78-011638725e02,1.0,44.361540,-79.656586,164692100.0,13.605256,IN_TRANSIT_TO,1701612377,154e218a-25ca-4fef-96d4-ae326234ea86,2202,4
25,656c8ba3cf3742cf5526e490,3f6631d0-bf40-448f-ab56-0b968ddaad17,aecd6920-d909-4f9b-9abd-975082fda027,SCHEDULED,1615e5c0-3157-4f13-9e78-011638725e02,1.0,44.360962,-79.655880,164692200.0,74.000000,IN_TRANSIT_TO,1701612407,154e218a-25ca-4fef-96d4-ae326234ea86,2202,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4060,656d3209cf3742cf5526f453,c4b80d50-75ac-40ba-a070-72d6d9de9b63,46075a10-f554-409b-9889-92d9cb82e032,SCHEDULED,1615e5c0-3157-4f13-9e78-011638725e02,1.0,44.373905,-79.690120,532988299.0,124.000000,IN_TRANSIT_TO,1701655011,3fc855e2-62ed-4e6f-8af1-d686a89f1cdd,1707,0
4073,656d320dcf3742cf5526f460,5af54e49-d005-4cbf-90e4-bc42b52593ad,c43aa90a-8ba3-4996-91ae-31904f9535e4,SCHEDULED,605702ef-34fb-4f95-bc52-25022968f4af,1.0,44.333805,-79.691360,714872399.0,11.382577,IN_TRANSIT_TO,1701655011,8ef473de-4b97-43c9-8b93-c61d17c90d54,1503,4
4075,656d322ccf3742cf5526f462,3f6631d0-bf40-448f-ab56-0b968ddaad17,969759f8-2cff-4b39-8c2c-c36420896266,SCHEDULED,605702ef-34fb-4f95-bc52-25022968f4af,1.0,44.413610,-79.668724,164927000.0,5.110131,IN_TRANSIT_TO,1701655041,7d3a9d37-8c8b-48e4-aa54-d73b109d5e0c,2202,4
4078,656d322dcf3742cf5526f465,c4b80d50-75ac-40ba-a070-72d6d9de9b63,46075a10-f554-409b-9889-92d9cb82e032,SCHEDULED,1615e5c0-3157-4f13-9e78-011638725e02,1.0,44.373910,-79.690070,532988299.0,124.000000,IN_TRANSIT_TO,1701655041,3fc855e2-62ed-4e6f-8af1-d686a89f1cdd,1707,0
4091,656d3230cf3742cf5526f472,5af54e49-d005-4cbf-90e4-bc42b52593ad,c43aa90a-8ba3-4996-91ae-31904f9535e4,SCHEDULED,605702ef-34fb-4f95-bc52-25022968f4af,1.0,44.334160,-79.689760,714872599.0,9.003776,IN_TRANSIT_TO,1701655041,30e66a4f-1be0-4511-a636-639db1a96417,1503,4

In [17]:
df.to_csv("test.csv", index=False)

In [18]:
part_1 = df.iloc[:125, :]
part_2 = df.iloc[125:250, :]
part_3 = df.iloc[250:375, :]
part_4 = df.iloc[375:, :]

# Save each part to a new CSV file
part_1.to_csv('part_1.csv', index=False)
part_2.to_csv('part_2.csv', index=False)
part_3.to_csv('part_3.csv', index=False)
part_4.to_csv('part_4.csv', index=False)